spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/interviewtracking
        username: postgres
<<<<<<< HEAD
        password: 12345
=======
        password: root
>>>>>>> 8209d63be854ea836a85ef46b89613bf2dfb621f
        
    jpa:
        generate-ddl: true
        show-sql: true
        
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
