spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/interviewtracking
        username: postgres
<<<<<<< HEAD
        password: root
=======
        password: 12345
>>>>>>> cc54f859947e6bd9df66135f3ad87341b9728f65
        
    jpa:
        generate-ddl: true
        show-sql: true
        
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
